In [203]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
pd.set_option('display.max_columns', 1000)
pd.set_option('display.width', 1000)

In [204]:
import pandas as pd
import numpy as np
from numpy import linalg as la

In [205]:
# Copio la matriz de ejercicio que empieza asi: Tenemos 4 puntos en 5 dimensiones
# representados por la siguiente matriz...

# La desviacion estándar de la columna 5 es cero, los que trae problemas cuando debo dividir mas abajo.
# lista = [[1, 6, 2, 3, 2],[3, 4, 6, 1, 2],[5, 1, 10, 4, 2],[6, 0, 11, 2, 2]]
# La borro:
lista = [[1, 6, 2, 3],[3, 4, 6, 1],[5, 1, 10, 4],[6, 0, 11, 2]]
A = np.matrix(lista)
A

matrix([[ 1,  6,  2,  3],
        [ 3,  4,  6,  1],
        [ 5,  1, 10,  4],
        [ 6,  0, 11,  2]])

In [206]:
# Calculo el promedio de cada columna.
M = A.mean(0)
M

matrix([[3.75, 2.75, 7.25, 2.5 ]])

In [207]:
# Paso 1 del apunte, página 298.
# 1. Para cada elemento de la columna de Ai, restarle el promedio de dicha
# columna. Esto permite centrar los datos en el origen.
A1 = A - M
A1

matrix([[-2.75,  3.25, -5.25,  0.5 ],
        [-0.75,  1.25, -1.25, -1.5 ],
        [ 1.25, -1.75,  2.75,  1.5 ],
        [ 2.25, -2.75,  3.75, -0.5 ]])

In [208]:
# Calculo la desviacion estándar de cada columna.
# Paso 1: calcular la media.
# Paso 2: calcular el cuadrado de la distancia a la media para cada dato.
# Paso 3: sumar los valores que resultaron del paso 2.
# Paso 4: dividir entre el número de datos.
# Paso 5: sacar la raíz cuadrada.
S = A1.std(0)
S

matrix([[1.92028644, 2.384848  , 3.56195171, 1.11803399]])

In [209]:
# Paso 2 del apunte, página 298.
# 2. Para cada elemento de la columna Ai, dividirlo por la desviación estándar
# de dicha columna. Esto permite escalar los datos.
A2 = A1 / S
A2

matrix([[-1.43207802,  1.36277029, -1.47391105,  0.4472136 ],
        [-0.39056673,  0.52414242, -0.3509312 , -1.34164079],
        [ 0.65094455, -0.73379939,  0.77204865,  1.34164079],
        [ 1.1717002 , -1.15311332,  1.05279361, -0.4472136 ]])

In [210]:
# Paso 3 del apunte, página 298.
# 3. Calcular la matriz de covarianza
# cov(A) = (1 / (n − 1)) * At * A
n = 5.
A3 = (1./(n-1.))*A2.T*A2
A3

matrix([[ 1.        , -0.99626795,  0.99598426,  0.05822225],
        [-0.99626795,  1.        , -0.99326482, -0.14064217],
        [ 0.99598426, -0.99326482,  1.        ,  0.09416472],
        [ 0.05822225, -0.14064217,  0.09416472,  1.        ]])

In [211]:
# Pearson correlation coefficient
# Calculo con numpy para verificar que hice bien los cálculos
# Con corrcoef me da distinto sino paso la transpuesta, ya que trabaja sobre las filas (igual que np.cov) 
np.corrcoef(A.T)

array([[ 1.        , -0.99626795,  0.99598426,  0.05822225],
       [-0.99626795,  1.        , -0.99326482, -0.14064217],
       [ 0.99598426, -0.99326482,  1.        ,  0.09416472],
       [ 0.05822225, -0.14064217,  0.09416472,  1.        ]])

In [ ]:
# La pregunta es:
# Calcular la matriz de covarianza y aplicar PCA. Luego identificar la opción correcta entre las siguientes.	 
#   a) La relación mas fuerte es entre la columna 1 y la 3.
#   b) No hay ningun cero en la matriz de covarianza.
#   c) La relación mas débil (ignorando valores nulos) se da entre la columna 1 y la 4
#   d) No es conveniente representar este set de datos en menos de 3 dimensiones.

In [ ]:
# Asi la opción a es falsa, las opciones b y c son verdaderas. Por lo que esto no puede estar bien.
# Pruebo trabajando sobre las filas.
# Ver pregunta en piazza "Duda con ejercicio de la guia de reduccion" https://piazza.com/class/jkr2voxi1yw4wt?cid=37

In [212]:
# Pearson correlation coefficient
# Pruebo calculando con las filas (y ahora completas, no existe más el problema de generar ceros)

lista = [[1, 6, 2, 3, 2],[3, 4, 6, 1, 2],[5, 1, 10, 4, 2],[6, 0, 11, 2, 2]]
A = np.matrix(lista)
A
np.corrcoef(A)

array([[ 1.        ,  0.08108108, -0.54105255, -0.6169527 ],
       [ 0.08108108,  1.        ,  0.61516934,  0.67627507],
       [-0.54105255,  0.61516934,  1.        ,  0.96957877],
       [-0.6169527 ,  0.67627507,  0.96957877,  1.        ]])

In [213]:
# Así las opciones a y c son falsas, b es verdadera y queda probar la d

In [214]:
from sklearn.decomposition import PCA

In [215]:
pca = PCA(n_components=4)
principalComponents = pca.fit_transform(A)
u, s, v = np.linalg.svd(A)

In [216]:
singular_values = s
energy_total = sum(singular_values**2)
sv_pow = singular_values**2
energy_percentage = ((sv_pow / energy_total) * 100)
print(energy_percentage)

[8.75864511e+01 1.12956726e+01 1.09775730e+00 2.01190239e-02]


In [217]:
acumulated_energy = 0
for i in range(len(energy_percentage)):
    acumulated_energy = acumulated_energy + energy_percentage[i]
    print ('Number of Singular Values ' + str(i+1) + ': ' + str(singular_values[i]) + ' ' + str(round(acumulated_energy,2)) + '%')

Number of Singular Values 1: 19.429297571923314 87.59%
Number of Singular Values 2: 6.977417066483102 98.88%
Number of Singular Values 3: 2.1751629706519973 99.98%
Number of Singular Values 4: 0.29447069991709524 100.0%


In [ ]:
# Con 3 dimensiones tengo casi un 100%, con 2 pierdo más del 1 porciento.

In [200]:
#calculo autovectores y autovalores
auto = la.eig(A3)
autovalores = auto[0]
autovectores = auto[1]

In [201]:
autovalores

array([ 3.00462792e+00,  9.89174218e-01, -1.16670940e-16,  6.19785716e-03])

In [202]:
autovectores

matrix([[ 0.57456257, -0.08841501, -0.77578921, -0.2453808 ],
        [-0.57635224,  0.00507641, -0.60216907,  0.55243528],
        [ 0.57499352, -0.0521087 ,  0.17987705,  0.79643668],
        [ 0.08413325,  0.99470684, -0.05646024,  0.01709201]])